source "https://rubygems.org"

ruby "~> 4.0.6"

gem "csv", "~> 3.3"
gem "kiba", "~> 4.0"
gem "nokogiri", "~> 1.16"
gem "rubyzip", "~> 3.4"
gem "puma", ">= 8.0.2"
gem "rackup", "~> 2.1"
gem "sinatra", "~> 4.0"

group :test do
  gem "minitest", "~> 5.0"
  gem "rake", "~> 13.0"
end

group :development do
  gem "brakeman", "~> 6.0", require: false
  gem "bundler-audit", "~> 0.9", require: false
  gem "standard", "~> 1.39", require: false
end
