require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.pattern = "test/**/*_test.rb"
  t.warning = false
end

desc "Lint with StandardRB"
task :standard do
  sh "bundle exec standardrb"
end

task default: %i[test standard]
